### ISSUE TITLE
output_node_name 얻는 방법, Tensorboard 실행 방법 질문입니다.

### ISSUE THREAD

**Issue by tucan9389** [jwkanggist/tensorflowlite#2]
`output_node_name: model_out/Softmax` 이라는 파라미터가 있는데, 이 파라미터는 Tensorboard로 확인해야할거같아 보입니다. Tensorboard를 실행해보는 과정에서 문제가 있어 질문드립니다.

#### 1. Tensorboard 실행
```shell
$ tensorboard --logdir pb_and_ckpt/runtrain-20180613-yglee/
```

##### 폴더 구조
```
...
pb_and_ckpt
   ├ runtrain-20180613-yglee
        ├ frozen_pb_out
        ├ checkpoint
        ├ net.ckpt.data-00000-of-00001
        ├ net.ckpt.index
        ├ net.ckpt.meta
        ├ net.pb
        ├ net.pbtxt
...
```

**Comment by tucan9389** [comment]
`run_fronzen_pb_convertor.py`를 실행하면 다음과같은 에러를 뱉습니다..

```shell
$ python run_fronzen_pb_convertor.py
# ------------------------------------------------
# [FreezeGraphConfig] input_dir_path: /Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/pb_and_ckpt/runtrain-20180613-yglee/
# [FreezeGraphConfig] output_dir_path: /Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/pb_and_ckpt/runtrain-20180613-yglee/frozen_pb_out/
# [FreezeGraphConfig] input_pb_name: net.pb
# [FreezeGraphConfig] input_ckpt_name: net.pbtxt
# [FreezeGraphConfig] output_pb_name: frozen_net.pb
# [FreezeGraphConfig] output_node_name: model_out/Softmax
# ------------------------------------------------
2018-06-15 01:55:23.684658: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-15 01:55:23.686874: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/pb_and_ckpt/runtrain-20180613-yglee/net.pbtxt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "run_fronzen_pb_convertor.py", line 41, in <module>
    tflite_convertor.convert_to_frozen_graph()
  File "/Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/convertor/tflite_convertor.py", line 224, in convert_to_frozen_graph
    initializer_nodes="")
  File "/Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 254, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 117, in freeze_graph_with_def_protos
    reader = pywrap_tensorflow.NewCheckpointReader(input_checkpoint)
  File "/Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 290, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /Users/canapio/Project/machine learning/MoT Labs/github_project/tensorflowlite/pb_and_ckpt/runtrain-20180613-yglee/net.pbtxt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```

**Comment by tucan9389** [comment]
https://github.com/tucan9389/tensorflowlite/commit/7965b0b405de8fb70448b4d87695c973115550ba#diff-0b3cb2f904539dafd42e4b758c0efb01
`run_fronzen_pb_convertor.py`에서 제가 수정한 부분입니다.

**Comment by tucan9389** [comment]
사용한 모델은 이것이구요
https://github.com/motlabs/dont-be-turtle/tree/develop/exportfiles/runtrain-20180613-yglee
